/* eslint-disable react-hooks/rules-of-hooks */
import { test as base, expect } from '@playwright/test';
import fs from 'fs';
import path from 'path';
import type { TestAuthTokens } from './seed-test-user';

// Read tokens generated by global setup
function getTestTokens(): TestAuthTokens {
  const tokensPath = path.join(__dirname, '.test-auth-tokens.json');
  if (!fs.existsSync(tokensPath)) {
    throw new Error(
      'Test auth tokens not found. Make sure global setup ran successfully.'
    );
  }
  return JSON.parse(fs.readFileSync(tokensPath, 'utf-8'));
}

// Extend base test with authenticated context
export const test = base.extend<{ authenticatedPage: typeof base }>({
  // Override the default page fixture to inject auth tokens
  page: async ({ page }, use) => {
    const tokens = getTestTokens();

    // Navigate to the app first (localStorage requires same origin)
    await page.goto('/');

    // Inject auth tokens into localStorage
    await page.evaluate(
      ({ accessToken, refreshToken }) => {
        localStorage.setItem('accessToken', accessToken);
        localStorage.setItem('refreshToken', refreshToken);
        localStorage.setItem('token', accessToken); // alias used by some code
      },
      tokens
    );

    // Reload to apply the auth state
    await page.reload();

    await use(page);
  },
});

export { expect };
